## q1:
Find a short Python expression to build the matrix
B =
$$\begin{pmatrix}
10 & 5 & 0 & -5\\
10 & 5 & 0 & -5\\
10 & 5 & 0 & -5\\
\end{pmatrix}$$

In [23]:
import numpy as np

arr1 = np.tile(np.arange(10, -6, -5), 3)
arr2 = np.resize(arr1, (3,3))
print(arr2)

[[10  5  0]
 [-5 10  5]
 [ 0 -5 10]]


## q2:
Find a short Python expression to build the matrix, using Matrix multiplication (
B =
$$\begin{pmatrix}
-2 & -2 & -2 \\
-1 & -1 & -1 \\
0 & 0 & 0 \\
1 & 1 & 1 \\
2 & 2 & 2 \\
\end{pmatrix}$$

In [ ]:
arr3 = np.repeat(-2, 4)
arr4 = np.resize(arr3, (3,4))
print(arr4)

[[-2 -2 -2]
 [-2 -2 -2]
 [-2 -2 -2]]


[[-2. -2. -2.]
 [-1. -1. -1.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]
 [ 2.  2.  2.]]
